const mongoose = require('mongoose'); // require Mongoose from MongoDB.

const BillingSchema = new mongoose.Schema({ // define new billing schema with...
  fullName: String, // ...full name as string...
  cardNumber: String, // ...card number as string...
  expirationDate: String, // ...expiration date as string...
  cvv: String,  // ...card verification value as string...
  billingAddress: String, // ...billing address as string...
  createdAt: { // ...and created at complex value with...
    type: Date, // ...type of date...
    default: Date.now // ...and default value as current time.
  }
});

module.exports = mongoose.model('Billing', BillingSchema);  // define schema called Billing with schema we made.
