const mongoose = require('mongoose'); // require Mongoose from MongoDB.

const ShippingSchema = new mongoose.Schema({  // define new schema with...
  fullName: String, // ...full name...
  address: String,  // ...address...
  city: String, // ...city...
  state: String,  // ...state...
  zip: String,  // ...ZIP...
  country: String,  // ...country...
  phone: String,  // ...phone number...
  email: String,  // ...email...
  createdAt: { type: Date, default: Date.now }  // ...and time created (default current date).
});

module.exports = mongoose.model('Shipping', ShippingSchema);  // create new model called Shipping with schema created.
